### ISSUE TITLE
Zen chooses different resolver for same link 

### ISSUE THREAD

**Issue by bjgood** [noobsandnerds/noobsandnerds#2]
Hi,
If I click on a link, using autoplay, it chooses a source-resolver as a first choice and then attempts to plays it. But, if I choose "Play using..." the list that it displays starts with a different source-resolver than what shows if you autoplay it.

Not a big deal, but it shows that its results are not consistent.

BTW, I really like Zen, and I use it all the time. It's far better than Exodus. :).

Thank you.

Regards,
Bob

**Comment by OpenELEQ** [comment]
Please post any error/bug reports in the appropriate support thread over on noobsandnerds.com (link to full debug log required) as this git is not being monitored.
Zen's support thread is located at http://noobsandnerds.com/support/showthread.php?tid=17217.
Thank you
