### ISSUE TITLE
why fuck it up ?

### ISSUE THREAD

**Issue by maildeamon** [noobsandnerds/noobsandnerds#3]
why did you screw up zen ? it worked fine now it sucks ?

**Comment by Andrewrb84** [comment]
actually the wrong zip was uploaded to the repo. things like this happen from time to time. the correct one will be uploaded and you will have a working version again but i doubt you will be back to say thanks for the update will you.

thanks for your ever so constructive feedback.

**Comment by OL282820** [comment]
maildeamon: Ungrateful ball-sack.

Andrewrb84: Thankfully, you guys have really thick skins. Ignore wankers like this.
p.s. Can I download individually as zip? If so, could you please tell me how? I've downloaded the master zip, but it fails to install.

**Comment by maildeamon** [comment]
when the update works i wil thank you ..... until now .....no sources ......where did al the hd link go ? i reinstaled old zen and everything workes great and plenty sources... now olmost no sources.....its not an improvement...... and im not the only one saying this a lot are complaining........

**Comment by Andrewrb84** [comment]
ever think the issue might be your end? zen works fine for me. try getting
an error log and explaining your issue so we can help you rather than being
a dick about it.

**Comment by Andrewrb84** [comment]
we should be pushing the new version Elysium should be getting released
pretty soon.

**Comment by maildeamon** [comment]
ok i admit i am wrong now i like the addon my apologies......

and another thing.....

thanks for the update :)
